MOCKED_TICKET_PRICE: float = 5.0
MOCKED_BANK_ERROR_RET: bool = False
MOCKED_BANK_SUCCESS_RET: bool = True

DEFAULT_FLIGHT_CODE_0: str = '00'
DEFAULT_FLIGHT_CODE_1: str = '01'
DEFAULT_FLIGHT_CODE_2: str = '02'
DEFAULT_NEW_FLIGHT_CODE: str = '03'
DEFAULT_FLIGHT_DESTINATION: str = 'ROMA'
DEFAULT_FLIGHT_PASSENGERS: int = 5

DEFAULT_FLIGHTS_LEN: int = 3
