from src.CardType import CardType
MOCKED_TICKET_PRICE: float = 5.0
MOCKED_BANK_ERROR_RET: bool = False
MOCKED_BANK_SUCCESS_RET: bool = True

DEFAULT_FLIGHT_CODE_0: str = '00'
DEFAULT_FLIGHT_CODE_1: str = '01'
DEFAULT_FLIGHT_CODE_2: str = '02'
DEFAULT_NEW_FLIGHT_CODE: str = '03'
DEFAULT_FLIGHT_DESTINATION: str = 'ROMA'
DEFAULT_FLIGHTS_LEN: int = 3

DEFAULT_NUM_TRAVELERS: int = 5
DEFAULT_FLIGHT_TOTAL_COST = DEFAULT_NUM_TRAVELERS * DEFAULT_FLIGHTS_LEN * MOCKED_TICKET_PRICE

DEFAULT_USER_NAME = "DEFAULT USER NAME"
DEFAULT_DNI = "12345678A"
DEFAULT_ADDRESS = "Calle Test, 1, 2.º A"
DEFAULT_MOBILE_NUMBER = "666777888"
DEFAULT_USER_EMAIL = "default@email.test"

DEFAULT_CARD_HOLDER_NAME = "DEFAULT NAME"
DEFAULT_CARD_NUMBER = "4556357956413441"
DEFAULT_CARD_CVV = "000"
DEFAULT_PAYMENT_AMOUNT = 5.0
DEFAULT_CARD_TYPE: CardType = CardType.VISA
