MOCKED_TICKET_PRICE: float = 5.0
MOCKED_HOTEL_PRICE: float = 6.0
MOCKED_CAR_PRICE: float = 3.0
MOCKED_BANK_ERROR_RET: bool = False
MOCKED_BANK_SUCCESS_RET: bool = True
DEFAULT_MAX_RETRIES: int = 4

DEFAULT_FLIGHT_CODE_0: str = '00'
DEFAULT_FLIGHT_CODE_1: str = '01'
DEFAULT_FLIGHT_CODE_2: str = '02'
DEFAULT_NEW_FLIGHT_CODE: str = '03'
DEFAULT_FLIGHT_DESTINATION: str = 'ROMA'
DEFAULT_FLIGHTS_LEN: int = 3

DEFAULT_NUM_TRAVELERS: int = 5

DEFAULT_CAR_CODE_0: str = '1234ABC'
DEFAULT_CAR_CODE_1: str = '5678BAT'
DEFAULT_NEW_CAR_CODE: str = '4554MAN'
DEFAULT_CAR_BRAND: str = 'DEFAULT BRAND'
DEFAULT_CAR_PICK_UP_PLACE: str = 'Calle Test, 2, 4.º B'
DEFAULT_CAR_DAYS_RESERVED: int = 3
DEFAULT_CARS_LEN: int = 2

DEFAULT_HOTEL_CODE_0: str = '00'
DEFAULT_HOTEL_CODE_1: str = '01'
DEFAULT_HOTEL_CODE_2: str = '02'
DEFAULT_HOTEL_NAME_0: str = 'aa'
DEFAULT_HOTEL_NAME_1: str = 'bb'
DEFAULT_HOTEL_NAME_2: str = 'cc'
DEFAULT_HOTEL_DAYS_RESERVED = 3
DEFAULT_HOTELS_LEN: int = 3

DEFAULT_USER_NAME = "DEFAULT USER NAME"
DEFAULT_DNI = "12345678A"
DEFAULT_ADDRESS = "Calle Test, 1, 2.º A"
DEFAULT_MOBILE_NUMBER = "666777888"
DEFAULT_USER_EMAIL = "default@email.test"

DEFAULT_CARD_HOLDER_NAME = "DEFAULT NAME"
DEFAULT_CARD_NUMBER = "4556 3579 5641 3441"
DEFAULT_CARD_CVV = "000"
DEFAULT_PAYMENT_AMOUNT = 5.0
DEFAULT_CARD_TYPE: str = 'VISA'

DEFAULT_FLIGHT_TOTAL_COST = DEFAULT_NUM_TRAVELERS * DEFAULT_FLIGHTS_LEN * MOCKED_TICKET_PRICE
DEFAULT_HOTEL_TOTAL_COST = DEFAULT_HOTELS_LEN * MOCKED_HOTEL_PRICE
DEFAULT_CAR_TOTAL_COST = DEFAULT_CARS_LEN * MOCKED_CAR_PRICE

DEFAULT_RETRIES = 2
